[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
systems_robot = ["*/*.robot"]

[project]
name = "systems_robot"
version = "0.0.1"
dependencies = [
    "robotframework",
]
