[build-system]
requires = [<s>"setuptools>=45"</s>, <s>"setuptools_scm[toml]>=6.2"</s>]
[tool.setuptools_scm]
[project]
name = "systems_robot"
version = "0.0.1"
dependencies = [
    "robotframework",
]
